# Generated by Django 5.1.3 on 2024-11-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferencia', '0003_ingresodedinero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transferencia',
            old_name='timestamp',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='transferencia',
            old_name='cantidad',
            new_name='monto',
        ),
        migrations.AddField(
            model_name='transferencia',
            name='comprobante',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='IngresoDeDinero',
        ),
    ]
