# Generated by Django 5.1.3 on 2024-11-26 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferencia', '0004_rename_timestamp_transferencia_fecha_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferencia',
            name='emisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_emitidas', to=settings.AUTH_USER_MODEL),
        ),
    ]
