# Generated by Django 5.1.3 on 2024-11-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0002_movimiento_delete_movimientogeneral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='referencia_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
