# Generated by Django 5.1.3 on 2024-11-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0003_alter_movimiento_referencia_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
