# Generated by Django 5.1.3 on 2024-11-26 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0004_movimiento_monto'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='receptor',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
