# Generated by Django 5.1.3 on 2024-11-26 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0005_movimiento_receptor_alter_movimiento_monto'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='comprobante',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
