# Generated by Django 5.1.3 on 2024-11-27 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0007_alter_movimiento_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
