# Generated by Django 5.1.3 on 2024-11-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0008_alter_movimiento_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='tipo',
            field=models.CharField(choices=[('ingreso', 'Ingreso de dinero'), ('transferencia_enviada', 'Transferencia enviada'), ('transferencia_recibida', 'Transferencia recibida')], max_length=30),
        ),
    ]
