# Generated by Django 5.1.3 on 2024-11-28 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_rename_balance_usuario_saldo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/avatar_default.jpeg', upload_to='avatars/'),
        ),
    ]
